var chai = require('chai');
var chaiHttp = require('chai-http');
var http = require('../index');

//Assertion Style
chai.should();

chai.use(chaiHttp);

describe('Poker hand api', () =>{

    describe("POST /api/v1/hand", () => {
        it("It should get the result of the mach", (done) =>{

            const jugada = [
                {
                   "jugadas":[
                      {
                         "jugador":"Cristiano",
                         "apuesta":1000,
                         "cartas":[
                            {
                               "valor":"2",
                               "palo":"H"
                            },
                            {
                               "valor":"3",
                               "palo":"D"
                            },
                            {
                               "valor":"5",
                               "palo":"S"
                            },
                            {
                               "valor":"9",
                               "palo":"C"
                            },
                            {
                               "valor":"K",
                               "palo":"D"
                            }
                         ]
                      },
                      {
                         "jugador":"Neymar",
                         "apuesta":20000,
                         "cartas":[
                            {
                               "valor":"2",
                               "palo":"C"
                            },
                            {
                               "valor":"3",
                               "palo":"H"
                            },
                            {
                               "valor":"4",
                               "palo":"S"
                            },
                            {
                               "valor":"8",
                               "palo":"C"
                            },
                            {
                               "valor":"A",
                               "palo":"H"
                            }
                         ]
                      }
                   ],
                   "bote":10000
                },
                {
                   "jugadas":[
                      {
                         "jugador":"Cristiano",
                         "apuesta":1000,
                         "cartas":[
                            {
                               "valor":"2",
                               "palo":"H"
                            },
                            {
                               "valor":"3",
                               "palo":"D"
                            },
                            {
                               "valor":"5",
                               "palo":"S"
                            },
                            {
                               "valor":"9",
                               "palo":"C"
                            },
                            {
                               "valor":"K",
                               "palo":"D"
                            }
                         ]
                      },
                      {
                         "jugador":"Neymar",
                         "apuesta":20000,
                         "cartas":[
                            {
                               "valor":"2",
                               "palo":"D"
                            },
                            {
                               "valor":"3",
                               "palo":"H"
                            },
                            {
                               "valor":"5",
                               "palo":"C"
                            },
                            {
                               "valor":"9",
                               "palo":"S"
                            },
                            {
                               "valor":"K",
                               "palo":"H"
                            }
                         ]
                      }
                   ],
                   "bote":0
                },
                {
                   "jugadas":[
                      {
                         "jugador":"Cristiano",
                         "apuesta":1000,
                         "cartas":[
                            {
                               "valor":"2",
                               "palo":"H"
                            },
                            {
                               "valor":"4",
                               "palo":"S"
                            },
                            {
                               "valor":"4",
                               "palo":"C"
                            },
                            {
                               "valor":"2",
                               "palo":"D"
                            },
                            {
                               "valor":"4",
                               "palo":"H"
                            }
                         ]
                      },
                      {
                         "jugador":"Neymar",
                         "apuesta":20000,
                         "cartas":[
                            {
                               "valor":"2",
                               "palo":"S"
                            },
                            {
                               "valor":"8",
                               "palo":"S"
                            },
                            {
                               "valor":"A",
                               "palo":"S"
                            },
                            {
                               "valor":"Q",
                               "palo":"S"
                            },
                            {
                               "valor":"3",
                               "palo":"S"
                            }
                         ]
                      }
                   ],
                   "bote":21000
                },
                {
                   "jugadas":[
                      {
                         "jugador":"Cristiano",
                         "apuesta":1000,
                         "cartas":[
                            {
                               "valor":"2",
                               "palo":"H"
                            },
                            {
                               "valor":"3",
                               "palo":"D"
                            },
                            {
                               "valor":"5",
                               "palo":"S"
                            },
                            {
                               "valor":"9",
                               "palo":"C"
                            },
                            {
                               "valor":"K",
                               "palo":"D"
                            }
                         ]
                      },
                      {
                         "jugador":"Neymar",
                         "apuesta":20000,
                         "cartas":[
                            {
                               "valor":"2",
                               "palo":"C"
                            },
                            {
                               "valor":"3",
                               "palo":"H"
                            },
                            {
                               "valor":"4",
                               "palo":"S"
                            },
                            {
                               "valor":"8",
                               "palo":"C"
                            },
                            {
                               "valor":"K",
                               "palo":"H"
                            }
                         ]
                      },
                      {
                         "jugador":"Maradona",
                         "apuesta":40000,
                         "cartas":[
                            {
                               "valor":"2",
                               "palo":"H"
                            },
                            {
                               "valor":"4",
                               "palo":"D"
                            },
                            {
                               "valor":"3",
                               "palo":"S"
                            },
                            {
                               "valor":"7",
                               "palo":"C"
                            },
                            {
                               "valor":"A",
                               "palo":"D"
                            }
                         ]
                      }
                   ],
                   "bote":0
                }
             ]
            const responseResult = [
                'Neymar gana 31000€','Iguales','Neymar gana 63000€','Partida amañada'
            ]
            chai.request(http)
                .post("/api/v1/hand")
                .send(jugada)
                .end((err, response) => {
                    response.should.have.status(200);
                    response.body.should.be.a('object');
                    response.body.should.have.property('resultados');
                    response.body.resultados.forEach((result,index) => {
                        result.should.have.property('resultado').eq(responseResult[index])
                    });
                    done();
                })
        })
    })
})